name: CI

on: push

jobs:
  windows:
    name: Windows
    runs-on: windows-2022

    env:
      LUA_VERSIONS: '5.1.5'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Prepare environment
        run: bash ./.ci/install-env-windows

      - name: Build and test cffi
        run: bash ./.ci/build-cffi-windows

        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: build-5.1.5/
